### ISSUE TITLE
个人主页 无法滑动查看缺省图

### ISSUE THREAD

**Issue by WithoutFeeling** [Coding/Coding-iOS#15]
第一次进入 个人主页，没有冒泡， 无法滑动到底部查看缺省图。切换至话题 ，可以滑动。再次切换 冒泡，仍然无法滑动查看缺省图。

**Comment by wanghengheng** [comment]
缺省图本来就是在页面无内容的时候显示的，这个页面本来就有一些内容，缺省图主要是考虑大屏幕上的问题。。你干嘛要滑动去看这个图啊
