### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by lhkzhl** [Coding/Coding-iOS#16]
'ObjectiveGit/ObjectiveGit.h' file not found

**Comment by wangtian076** [comment]
objective-git这个东西需要cathage,所以要先把这个安装再运行bootstrap就不会再报错了

**Comment by lhkzhl** [comment]
电脑有装carthage 版本为0.29.0,不是这个原因，

**Comment by lhkzhl** [comment]
1.需要gitclone  不能直接下载，介绍里有，但是我当时没有注意 
2.需要vpn,不然，有些东西下载不下来

**Comment by lhkzhl** [comment]
已解决
