### ISSUE TITLE
能介绍一下多语言的实现方案么？

### ISSUE THREAD

**Issue by Eelson126** [Coding/Coding-iOS#17]
能介绍一下多语言的实现方案么？

**Comment by wanghengheng** [comment]
国际化么？。。Apple 有自己的推荐方案的啊。。CODING 暂时没有要做国际化的计划

**Comment by wanghengheng** [comment]
这个 App 没有支持多国语言啊。。推荐你个链接了解下：https://objccn.io/issue-9-3/
