### ISSUE TITLE
UMengAnalytics这个用不了，建议更新新版本的有盟库

### ISSUE THREAD

**Issue by semnyqu** [Coding/Coding-iOS#20]
UMengAnalytics这个用不了，建议更新新版本的有盟库

**Comment by semnyqu** [comment]
像AFN这样的基础库，能否直接使用pod加载

**Comment by wanghengheng** [comment]
AFN 不用 pod 是因为对源码有修改，是自己的需求点有点诡异，不是可以 pr 的那种

UMengAnalytics 我看最新版本就是 4.2.4 啊

**Comment by semnyqu** [comment]
UMengAnalytics是老版本库
#新版本友盟
    pod 'UMCCommon'
    pod 'UMCSecurityPlugins'
    pod 'UMCAnalytics'

**Comment by wanghengheng** [comment]
@semnyqu 不更了
